/**
 * The single ownership-checked write path for artifacts generated into the target
 * repo's own tree (e.g. public/llms.txt, page alternates). Per OPERATE.md: "Human-owned
 * files must not be overwritten without explicit ownership rules." Every generator must
 * route through this rather than calling writeFileSync directly.
 *
 * Files under .agentsurface/ are AgentSurface-owned outright (the tool's own working
 * directory) and do not need this — this is only for writes into the surrounding repo.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

export const OWNERSHIP_HEADER_PREFIX = "<!--\nGenerated by AgentSurface";

export function ownershipHeader(sourceModel: string): string {
  return `<!--\nGenerated by AgentSurface. Do not edit directly unless ownership is transferred.\nSource model: ${sourceModel}\n-->\n\n`;
}

export interface OwnedWriteResult {
  written: boolean;
  /** True when a pre-existing, non-AgentSurface-owned file blocked the write. */
  conflict: boolean;
}

export function writeOwned(path: string, content: string, overwriteHumanOwned: boolean): OwnedWriteResult {
  if (existsSync(path) && !overwriteHumanOwned) {
    const existing = readFileSync(path, "utf-8");
    if (!existing.startsWith(OWNERSHIP_HEADER_PREFIX)) {
      return { written: false, conflict: true };
    }
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, "utf-8");
  return { written: true, conflict: false };
}
