import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadConfig } from "../config.js";
import { extractContentBoundary, htmlToMarkdown } from "../lib/htmlToMarkdown.js";
import type { CanonicalSiteModel, RouteRecord } from "../types/model.js";

export interface GenerateOptions {
  repoRoot: string;
  /** Base URL of a running instance of the target site, used to fetch real rendered HTML. */
  serverBaseUrl: string;
}

export interface GenerateResult {
  generated: string[];
  skipped: { path: string; reason: string }[];
}

const OWNERSHIP_HEADER = (sourceModel: string) =>
  `<!--\nGenerated by AgentSurface. Do not edit directly unless ownership is transferred.\nSource model: ${sourceModel}\n-->\n\n`;

export async function runGenerate(opts: GenerateOptions): Promise<GenerateResult> {
  const config = loadConfig(opts.repoRoot);
  const modelPath = join(opts.repoRoot, ".agentsurface", "model", "routes.json");
  if (!existsSync(modelPath)) {
    throw new Error(`No model found at ${modelPath}. Run "agentsurface inspect" first.`);
  }
  const routes: RouteRecord[] = JSON.parse(readFileSync(modelPath, "utf-8"));

  const generatedDir = join(opts.repoRoot, ".agentsurface", "generated", "pages");
  mkdirSync(generatedDir, { recursive: true });

  const result: GenerateResult = { generated: [], skipped: [] };

  for (const route of routes) {
    if (route.contentType !== "page") {
      continue; // redirects and unknown content types are never mirrored
    }
    if (route.classification !== "public-static" && route.classification !== "public-dynamic") {
      result.skipped.push({ path: route.path, reason: `classification "${route.classification}" is not public; excluded by default` });
      continue;
    }
    if (route.dynamicSegments.length > 0) {
      result.skipped.push({ path: route.path, reason: "dynamic route; content-source extraction not implemented in this slice" });
      continue;
    }
    if (!route.contentBoundaryTag) {
      result.skipped.push({ path: route.path, reason: "no deterministic content boundary found in source; refusing to guess" });
      continue;
    }

    const url = new URL(route.path, opts.serverBaseUrl).toString();
    let html: string;
    try {
      const res = await fetch(url);
      if (!res.ok) {
        result.skipped.push({ path: route.path, reason: `fetch returned HTTP ${res.status}` });
        continue;
      }
      html = await res.text();
    } catch (err) {
      result.skipped.push({ path: route.path, reason: `fetch failed: ${err instanceof Error ? err.message : String(err)}` });
      continue;
    }

    const fragment = extractContentBoundary(html, route.contentBoundaryTag);
    if (fragment === null) {
      result.skipped.push({ path: route.path, reason: `rendered HTML did not contain a well-formed <${route.contentBoundaryTag}> boundary` });
      continue;
    }

    const markdown = htmlToMarkdown(fragment);
    const outFile = routePathToGeneratedFile(generatedDir, route.path);
    mkdirSync(join(outFile, ".."), { recursive: true });

    const content = OWNERSHIP_HEADER(".agentsurface/model/routes.json") + markdown + "\n";

    // Only ever overwrite files AgentSurface itself owns (carries its own header),
    // unless the config explicitly opts into overwriting human-owned output.
    if (existsSync(outFile) && !config.ownership.overwriteHumanOwned) {
      const existing = readFileSync(outFile, "utf-8");
      if (!existing.startsWith("<!--\nGenerated by AgentSurface")) {
        result.skipped.push({ path: route.path, reason: `${outFile} exists and is not AgentSurface-owned; refusing to overwrite` });
        continue;
      }
    }

    writeFileSync(outFile, content, "utf-8");
    result.generated.push(route.path);
  }

  generateLlmsTxt(opts.repoRoot, config, routes);

  return result;
}

function routePathToGeneratedFile(generatedDir: string, routePath: string): string {
  const clean = routePath === "/" ? "/index" : routePath;
  return join(generatedDir, clean + ".md");
}

function generateLlmsTxt(repoRoot: string, config: ReturnType<typeof loadConfig>, routes: RouteRecord[]): void {
  const publicPages = routes.filter(
    (r) => r.contentType === "page" && r.classification === "public-static" && r.dynamicSegments.length === 0
  );

  const lines: string[] = [];
  lines.push(`# ${config.site.name}`);
  lines.push("");
  lines.push("> Generated by AgentSurface from the current site structure. This is a discovery index, not a full content dump.");
  lines.push("");
  lines.push("## Pages");
  lines.push("");
  for (const r of publicPages) {
    const hasAlternate = r.contentBoundaryTag !== null;
    const label = r.path === "/" ? "Home" : r.path.replace(/^\//, "");
    if (hasAlternate) {
      lines.push(`- [${label}](${r.path}) — Markdown: ${r.path === "/" ? "/index.md" : r.path + ".md"}`);
    } else {
      lines.push(`- [${label}](${r.path})`);
    }
  }
  lines.push("");
  lines.push("## Structured data");
  lines.push("");
  lines.push("- [/api/values](/api/values) — site values, JSON");
  lines.push("");

  const outPath = join(repoRoot, "public", "llms.txt");
  const header = `<!-- Generated by AgentSurface. Source model: .agentsurface/model/routes.json -->\n`;
  writeFileSync(outPath, header + lines.join("\n") + "\n", "utf-8");
}
