import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { loadConfig } from "../config.js";
import { extractContentBoundary, htmlToMarkdown } from "../lib/htmlToMarkdown.js";
import type { RouteRecord } from "../types/model.js";

export interface ValidateOptions {
  repoRoot: string;
  /** If provided, re-fetches live pages to check for content drift against generated output. */
  serverBaseUrl?: string;
}

export interface ValidationFailure {
  check: "route-parity" | "discovery-integrity" | "ownership-safety" | "drift" | "capability-truthfulness";
  path: string;
  message: string;
}

export interface ValidateResult {
  failures: ValidationFailure[];
  checkedGeneratedFiles: number;
  checkedDiscoveryLinks: number;
}

const OWNERSHIP_PREFIX = "<!--\nGenerated by AgentSurface";

export async function runValidate(opts: ValidateOptions): Promise<ValidateResult> {
  loadConfig(opts.repoRoot); // ensures init has run; throws otherwise
  const modelPath = join(opts.repoRoot, ".agentsurface", "model", "routes.json");
  if (!existsSync(modelPath)) {
    throw new Error(`No model found at ${modelPath}. Run "agentsurface inspect" first.`);
  }
  const routes: RouteRecord[] = JSON.parse(readFileSync(modelPath, "utf-8"));
  const routesByPath = new Map(routes.map((r) => [r.path, r]));

  const failures: ValidationFailure[] = [];
  const generatedDir = join(opts.repoRoot, ".agentsurface", "generated", "pages");
  const generatedFiles = generatedDir && existsSync(generatedDir) ? listMarkdownFiles(generatedDir) : [];

  // --- Route parity + ownership safety ---
  for (const file of generatedFiles) {
    const routePath = generatedFileToRoutePath(generatedDir, file);
    const route = routesByPath.get(routePath);

    if (!route) {
      failures.push({
        check: "route-parity",
        path: routePath,
        message: `generated file ${file} has no corresponding route in the current model — stale output from a removed/renamed route`,
      });
      continue;
    }
    if (route.classification !== "public-static" && route.classification !== "public-dynamic") {
      failures.push({
        check: "route-parity",
        path: routePath,
        message: `route is now classified "${route.classification}" but a generated public file still exists for it — regenerate to remove`,
      });
    }

    const content = readFileSync(file, "utf-8");
    if (!content.startsWith(OWNERSHIP_PREFIX)) {
      failures.push({
        check: "ownership-safety",
        path: routePath,
        message: `${file} does not carry AgentSurface's ownership header — may have been hand-edited or is not actually AgentSurface-owned`,
      });
    }
  }

  // --- Discovery integrity: llms.txt links must resolve to real generated files ---
  const llmsTxtPath = join(opts.repoRoot, "public", "llms.txt");
  let checkedDiscoveryLinks = 0;
  if (existsSync(llmsTxtPath)) {
    const llmsTxt = readFileSync(llmsTxtPath, "utf-8");
    const mdRefs = [...llmsTxt.matchAll(/Markdown:\s*(\S+\.md)/g)].map((m) => m[1]);
    for (const ref of mdRefs) {
      checkedDiscoveryLinks++;
      const relFile = ref === "/index.md" ? "index.md" : ref.replace(/^\//, "");
      const abs = join(generatedDir, relFile);
      if (!existsSync(abs)) {
        failures.push({
          check: "discovery-integrity",
          path: ref,
          message: `llms.txt references ${ref}, but ${abs} does not exist`,
        });
      }
    }
  } else {
    failures.push({ check: "discovery-integrity", path: "/llms.txt", message: "public/llms.txt does not exist" });
  }

  // --- Drift detection: re-fetch live content and diff against what's on disk ---
  if (opts.serverBaseUrl) {
    for (const file of generatedFiles) {
      const routePath = generatedFileToRoutePath(generatedDir, file);
      const route = routesByPath.get(routePath);
      if (!route || !route.contentBoundaryTag) continue;

      const url = new URL(routePath, opts.serverBaseUrl).toString();
      try {
        const res = await fetch(url);
        if (!res.ok) continue;
        const html = await res.text();
        const fragment = extractContentBoundary(html, route.contentBoundaryTag);
        if (fragment === null) continue;
        const freshMarkdown = htmlToMarkdown(fragment);

        const onDisk = readFileSync(file, "utf-8");
        const onDiskMarkdown = onDisk.slice(onDisk.indexOf("-->") + 3).trim();
        if (freshMarkdown.trim() !== onDiskMarkdown) {
          failures.push({
            check: "drift",
            path: routePath,
            message: `live rendered content no longer matches generated output — source changed since last "agentsurface generate"`,
          });
        }
      } catch {
        // Server unreachable for this route; not a validation failure in itself.
      }
    }
  }

  return { failures, checkedGeneratedFiles: generatedFiles.length, checkedDiscoveryLinks };
}

function listMarkdownFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const abs = join(dir, entry);
    if (statSync(abs).isDirectory()) {
      out.push(...listMarkdownFiles(abs));
    } else if (entry.endsWith(".md")) {
      out.push(abs);
    }
  }
  return out;
}

function generatedFileToRoutePath(generatedDir: string, file: string): string {
  const rel = file.slice(generatedDir.length).replace(/\\/g, "/").replace(/\.md$/, "");
  return rel === "/index" ? "/" : rel;
}
